spring:
  application:
    name: management
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/management
    driver-class-name: org.h2.Driver
    username: sa


logbook:
  include:
    - /**
  format.style: json
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  filter.enabled: true
  exclude:
    - /customers/healthcheck

logging:
  level:
    org.zalando.logbook: trace

server:
  port: 9000