apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentar-fleet-deployment
  labels:
    app: rentar-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentar-fleet
  template:
    metadata:
      labels:
        app: rentar-fleet
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: kafka:9092
        image: denisolek/rentar-fleet:1.0.8
        name: rentar-fleet
        ports:
        - containerPort: 9001
      hostname: rentar-fleet
      restartPolicy: Always
