apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentar-management-deployment
  labels:
    app: rentar-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentar-management
  template:
    metadata:
      labels:
        app: rentar-management
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: kafka:9092
        image: denisolek/rentar-management:1.0.2
        name: rentar-management
        ports:
        - containerPort: 9000
      hostname: rentar-management
      restartPolicy: Always
