apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentar-rental-deployment
  labels:
    app: rentar-rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentar-rental
  template:
    metadata:
      labels:
        app: rentar-rental
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: kafka:9092
        image: denisolek/rentar-rental:1.0.2
        name: rentar-rental
        ports:
        - containerPort: 9002
      hostname: rentar-rental
      restartPolicy: Always
