apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentar-web-deployment
  labels:
    app: rentar-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentar-web
  template:
    metadata:
      labels:
        app: rentar-web
    spec:
      containers:
      - image: denisolek/rentar-web:1.0.2
        name: rentar-web
        ports:
        - containerPort: 80
      hostname: rentar-web
      restartPolicy: Always
