kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: generic
  resources:
    requests:
      storage: 8Gi
