kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-data
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes-data/grafana"